---

all:
  hosts:
    server-01:
      ansible_host: server-01.provision
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ../resources/keys/id_ubuntu
      ansible_ssh_common_args: -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile /dev/null"
      ansible_become: yes
    server-02:
      ansible_host: server-02.provision
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ../resources/keys/id_ubuntu
      ansible_ssh_common_args: -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile /dev/null"
      ansible_become: yes
